# Generated by Scripts/generate-homebrew-cask.py from
# Configuration/published-release.json. Do not hand-edit: `--check` fails when
# this no longer matches the published release.
cask "coretend" do
  version "1.0.1"
  sha256 "91026c89313e7b36a546b395ae4ba21dee2542e0e7592c22a0cec8cdb5d86fde"

  url "https://github.com/ahmetbsbnr/coretend/releases/download/v#{version}/CoreTend-#{version}-arm64.dmg",
      verified: "github.com/ahmetbsbnr/coretend/"
  name "CoreTend"
  desc "Local, transparent and reversible storage care for macOS"
  homepage "https://coretend.ahmetbsbnr.com/"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on macos: ">= :sonoma"
  depends_on arch: :arm64

  app "CoreTend.app"

  # macOS caches app icons aggressively in LaunchServices, so a reinstall or
  # an upgrade can leave the Dock and Launchpad showing the previous icon.
  # Re-registering the bundle costs nothing and removes a support question
  # that has nothing to do with the app.
  postflight do
    system_command "/System/Library/Frameworks/CoreServices.framework/Versions/A/" \
                   "Frameworks/LaunchServices.framework/Versions/A/Support/lsregister",
                   args: ["-f", "#{appdir}/CoreTend.app"],
                   sudo: false
  end

  # The paths CoreTend owns outside its bundle, taken from what
  # `Scripts/uninstall.sh` actually removes rather than from memory. The first
  # draft of this cask said "exactly two" and was wrong: the pre-rename product
  # left its own support directory and preferences, and a cask that ignores
  # them leaves data behind for precisely the users who have been here longest.
  # `uninstall.sh` treats the legacy pair as opt-in; `zap` is the explicit
  # "remove everything" verb, so here they belong.
  uninstall quit: "com.ahmetbsbnr.coretend"

  zap trash: [
    "~/Library/Application Support/CoreTend",
    "~/Library/Preferences/com.ahmetbsbnr.coretend.plist",
    "~/Library/Application Support/MacCareLocal",
    "~/Library/Application Support/MacCare Local",
    "~/Library/Preferences/local.maccare.app.plist",
  ]
end
