#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: The CoreTend Authors
"""Generates Documentation/Audits/UI_INVENTORY.md from the sources.

An audit written by hand is out of date at the next commit, and an inventory
recalled from memory is an inventory of what someone remembers. This walks the
tree instead, so every number in the report can be re-derived by running it.

Stdlib only, no network, no build required.
"""
import pathlib, re, collections, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
APP = ROOT / "Sources/CoreTendApp"
DS = ROOT / "Sources/DesignSystem"
STRINGS = {lang: APP / f"Resources/{lang}.lproj/Localizable.strings" for lang in ("Base", "fr")}

# Views the user can actually land on, keyed by the module they back.
MODULE_VIEWS = {
    "Overview": "DashboardView.swift", "Record": "RecordView.swift",
    "Cleanup": "CleanupView.swift", "Explore": "SpaceLensView.swift",
    "Duplicates": "DuplicatesView.swift", "Applications": "ApplicationsView.swift",
    "Integrity": "ProtectionView.swift", "Performance": "PerformanceView.swift",
}

def read(p):
    return p.read_text(encoding="utf-16" if p.suffix == ".strings" else "utf-8")

def strings(lang):
    out = {}
    for line in read(STRINGS[lang]).split("\n"):
        m = re.match(r'^"([^"]+)"\s*=\s*"(.*)";\s*$', line)
        if m:
            out[m.group(1)] = m.group(2)
    return out

def swift_sources():
    return sorted(p for p in (ROOT / "Sources").rglob("*.swift"))

def main():
    app_src = {p.name: read(p) for p in APP.rglob("*.swift")}
    all_src = {str(p.relative_to(ROOT)): read(p) for p in swift_sources()}
    code = "\n".join(all_src.values())
    out = []
    w = out.append

    w("# UI inventory\n")
    w("Generated by `Scripts/audit-ui.py`. Do not edit by hand — re-run it.\n")

    # --- 1. module surface coverage -------------------------------------
    w("## 1. Module surfaces\n")
    w("What each landing view actually provides. A blank cell is a gap, not a style choice.\n")
    w("| Module | Lines | Toolbar | Empty state | Loading | Error | Sub-nav | a11y labels |")
    w("|---|---:|:-:|:-:|:-:|:-:|:-:|---:|")
    gaps = collections.Counter()
    for module, filename in MODULE_VIEWS.items():
        s = app_src.get(filename, "")
        def has(pattern, key):
            found = bool(re.search(pattern, s))
            if not found:
                gaps[key] += 1
            return "yes" if found else "—"
        row = [module, str(s.count("\n")),
               has(r"\.toolbar", "toolbar"), has(r"MCEmptyState", "empty"),
               has(r"ProgressView", "loading"), has(r"failed|error", "error"),
               has(r"ModuleSubNav|MCModuleSubNav", "subnav")]
        row.append(str(len(re.findall(r"accessibilityLabel", s))))
        w("| " + " | ".join(row) + " |")
    w("")
    w("**Gaps across %d modules:** " % len(MODULE_VIEWS)
      + ", ".join(f"no {k} ×{v}" for k, v in gaps.most_common()) + ".\n")

    # --- 2. design-system leakage ---------------------------------------
    w("## 2. Where the design system is bypassed\n")
    # Code only: a comment explaining why a value was removed is not a use of
    # it, and counting one made the report claim a literal that is not there.
    app_only = "\n".join(
        "\n".join(l for l in v.split("\n") if not l.strip().startswith("//"))
        for k, v in all_src.items() if "/CoreTendApp/" in k)
    opacities = collections.Counter(re.findall(r"\.opacity\(([0-9.]+)\)", app_only))
    paddings = collections.Counter(re.findall(r"\.padding\((?:\.\w+,\s*)?(\d+)\)", app_only))
    # \b, or `grantColor(` counts as a raw Color construction — the report
    # claimed two that did not exist.
    raw_colors = re.findall(r"\bColor\((?![.)])", app_only)
    w(f"- **{sum(opacities.values())} opacity literals**, {len(opacities)} distinct values: "
      + ", ".join(f"`{v}`×{n}" for v, n in opacities.most_common()) + ".")
    w(f"  None is a token. Each is an unmeasured local decision.")
    w(f"- **{sum(paddings.values())} numeric paddings** bypassing `MCSpacing`: "
      + ", ".join(f"`{v}`×{n}" for v, n in paddings.most_common()) + ".")
    w(f"- **{len(raw_colors)} raw `Color(...)` constructions** outside DesignSystem.\n")

    # --- 3. typography coherence ----------------------------------------
    ds_typo = read(DS / "Typography.swift")
    absolute = re.findall(r"Font\.system\(size:\s*(\d+)", ds_typo)
    dynamic = re.findall(r"Font\.(title\d?|body|callout|caption\d?|headline|subheadline|footnote)", ds_typo)
    w("## 3. Typography\n")
    w(f"- **{len(absolute)} absolute sizes** ({', '.join(sorted(set(absolute), key=int))} pt) alongside "
      f"**{len(dynamic)} Dynamic Type styles**.")
    w("  Absolute sizes do not respond to the system text size. Mixing the two means the")
    w("  interface partially scales, which is worse than either choice made consistently.\n")

    # --- 4. iconography --------------------------------------------------
    symbols = collections.Counter(
        re.findall(r'systemImage:\s*"([^"]+)"', code) + re.findall(r'systemName:\s*"([^"]+)"', code))
    reused = {s: n for s, n in symbols.items() if n > 1}
    w("## 4. Iconography\n")
    w(f"- **{len(symbols)} distinct SF Symbols**, {sum(symbols.values())} uses.")
    w(f"- **{len(reused)} symbols carry more than one meaning**: "
      + ", ".join(f"`{s}`×{n}" for s, n in sorted(reused.items(), key=lambda kv: -kv[1])[:10]) + ".")
    w("  A symbol used for both a module and an illustration teaches the user nothing.\n")

    # --- 5. copy: claims the app cannot back ----------------------------
    w("## 5. Copy that claims more than the app knows\n")
    w("`\"Freed (real)\"` shipped: it summed bytes moved to the Trash and called the sum")
    w("verified. These are every other string of that shape — each needs a decision, not")
    w("a glance.\n")
    CLAIMS = {
        "en": r"\b(freed|reclaim\w*|recovered|verified|guarantee\w*|ensure[sd]?|safe(?:ly)?|"
              r"complete(?:ly)?|all|every|permanent\w*|optimi[sz]\w*|speed\w* up|boost\w*)\b",
        "fr": r"\b(libér\w+|récupér\w+|vérifi\w+|garanti\w*|assur\w+|sûr\w*|sans risque|"
              r"complet\w*|tous|toutes|chaque|définitiv\w+|optimis\w+|accélér\w+)\b",
    }
    for lang, key in (("Base", "en"), ("fr", "fr")):
        table = strings(lang)
        hits = [(k, v) for k, v in sorted(table.items())
                if re.search(CLAIMS[key], v, re.I)]
        w(f"### {lang} — {len(hits)} of {len(table)} strings\n")
        w("| Key | String |")
        w("|---|---|")
        for k, v in hits:
            w(f"| `{k}` | {v.replace('|', chr(92) + '|')} |")
        w("")

    # --- 6. localization health -----------------------------------------
    base, fr = strings("Base"), strings("fr")
    used = set(re.findall(r'L\(\s*"([^"]+)"', code))
    w("## 6. Localization\n")
    w(f"- Base **{len(base)}** keys · fr **{len(fr)}** keys.")
    missing_fr = sorted(set(base) - set(fr))
    missing_en = sorted(set(fr) - set(base))
    w(f"- Only in Base: {len(missing_fr)} {missing_fr[:8] or ''}")
    w(f"- Only in fr: {len(missing_en)} {missing_en[:8] or ''}")
    orphans = sorted(set(base) - used)
    w(f"- **{len(orphans)} defined but never referenced** — dead weight carried in two languages.")
    w(f"  Sample: {orphans[:12]}")
    undefined = sorted(used - set(base))
    w(f"- **{len(undefined)} referenced but undefined**: {undefined or 'none'}")
    # length divergence: French is typically longer; flag the extremes.
    ratios = [(len(fr[k]) / max(len(base[k]), 1), k) for k in base if k in fr and len(base[k]) > 12]
    ratios.sort(reverse=True)
    w(f"- Longest French relative to English (layout risk): "
      + ", ".join(f"`{k}` ×{r:.1f}" for r, k in ratios[:6]) + "\n")

    path = ROOT / "Documentation/Audits/UI_INVENTORY.md"
    path.write_text("\n".join(out) + "\n")
    print(path)

main()
