from pathlib import Path
import os
root = Path(__file__).resolve().parents[1]
os.chdir(root)
pages={
'en':{
'home':('A calmer way to understand your Mac','CoreTend is a local-first macOS disk and system explorer. This reconstruction is an unreleased local preview.','Current work','The preview scans folders you select, shows measured sizes and exact duplicates, previews chosen files, and filters large or older items. It never changes files during a scan.','Eight destinations','Overview, Record, Cleanup, Explore, Duplicates, Applications, Integrity, and Performance define the product scope. Several workflows are implemented; broader permission, accessibility and release qualification remain open.'),
'features':('Product scope','Eight destinations define the complete target. Only behavior marked as implemented in the local project has working code today.','Available in local preview','Chosen-folder scans with exclusions; Explore search, sort, proportional map, Quick Look and explicit size/age filters; reviewed Trash workflows for exact duplicates, cleanup and chosen app bundles; advisory similar-image pairs; app inventory, declared HTTPS feed and signature signal; local event records and manual performance history; read-only CLI with explicit partial-scan status.','Still to build','Verified app-data attribution and complete uninstall, App Store update source and version comparison, cloud storage details, native accessibility qualification, signed distribution and broader migration evidence.'),
'privacy':('Privacy by design','CoreTend is designed to work locally. This unreleased reconstruction sends no telemetry and has no account or cloud sync. A declared update feed opens in your browser only when you click its link.','File access','The app preview scans only a folder you select. Scans read metadata and file contents only when needed for exact duplicate hashing. A scan never writes to the selected tree.','Actions and records','File actions require review and confirmation, revalidate each target, and use macOS Trash only. Event records and manual performance samples stay local; event retention and the full export UI still need qualification.'),
'support':('Support','This reconstruction branch is public source, not a released product. Use repository issues for source feedback.','For maintainers','Use the developer notes and test suite in the source repository. Report build failures with macOS version, architecture, command, and complete error output. Do not attach private file paths or database contents.','Before reporting','This reconstruction has no released download or product support commitment.'),
'developer':('Developer notes','Build and test locally with Swift 6 and Swift Package Manager. No runtime package dependencies are used.','Commands','Run `swift test`, `swift build --product CoreTendApp`, and `swift build --product CoreTendCLI` from the reconstruction repository. Tests create unique temporary fixtures.','Safety boundary','Do not test against a real home directory, CoreTend store, or Trash. The production Trash adapter is not called by tests. The next branch is public source. Signing, notarization, release tags, and distribution remain separate gates.')},
'fr':{
'home':('Comprendre son Mac avec plus de clarté','CoreTend explore localement le disque et certains signaux système sur macOS. Cette reconstruction est un aperçu local non publié.','Travail actuel','L’aperçu analyse les dossiers choisis, affiche tailles et doublons exacts, prévisualise les fichiers retenus et filtre les plus volumineux ou anciens. Une analyse ne modifie jamais les fichiers.','Huit destinations','Vue d’ensemble, Historique, Nettoyage, Explorer, Doublons, Applications, Intégrité et Performances composent le périmètre. Plusieurs parcours fonctionnent; permissions avancées, accessibilité et qualification de release restent ouvertes.'),
'features':('Périmètre produit','Huit destinations forment la cible complète. Seuls les comportements déclarés comme implémentés dans le projet local fonctionnent aujourd’hui.','Disponible dans l’aperçu local','Analyses avec exclusions; recherche, tri, carte proportionnelle, Quick Look et filtres explicites dans Explorer; revue et Corbeille pour doublons, nettoyage et bundle choisi; images similaires consultatives; inventaire, flux HTTPS déclaré et signature; historique local, mesures manuelles et CLI lecture seule avec état partiel explicite.','Reste à construire','Attribution vérifiée des données d’apps et désinstallation complète, source App Store et comparaison des versions, détails cloud, qualification native d’accessibilité, distribution signée et preuves de migration plus larges.'),
'privacy':('Confidentialité dès la conception','CoreTend est conçu pour fonctionner localement. Cette reconstruction non publiée n’envoie aucune télémétrie et ne propose ni compte ni synchronisation cloud. Un flux de mise à jour déclaré s’ouvre dans votre navigateur seulement après un clic.','Accès aux fichiers','L’aperçu analyse uniquement le dossier que vous choisissez. Il lit les métadonnées et le contenu seulement si nécessaire pour comparer exactement les doublons. Une analyse n’écrit jamais dans le dossier choisi.','Actions et historique','Les actions demandent revue et confirmation, revalident chaque cible et utilisent seulement la Corbeille macOS. Événements et mesures Performance manuelles restent locaux; conservation des événements et export complet demandent encore qualification.'),
'support':('Assistance','La branche de reconstruction est publique en source, sans produit distribué. Utilisez les issues du dépôt pour les retours sur le code.','Pour les mainteneurs','Consultez les notes de développement et la suite de tests dans le dépôt source. Pour un échec, joignez la version de macOS, l’architecture, la commande et le message complet. Ne joignez pas de chemins privés ni de base contenant vos données.','Avant tout signalement','Cette reconstruction ne propose aucun téléchargement publié ni engagement de support produit.'),
'developer':('Notes de développement','Construisez et vérifiez localement avec Swift 6 et Swift Package Manager. Aucune dépendance runtime externe.','Commandes','Depuis le dépôt de reconstruction : `swift test`, `swift build --product CoreTendApp` et `swift build --product CoreTendCLI`. Les tests créent des fixtures temporaires uniques.','Frontière de sûreté','Ne lancez pas les tests sur un vrai dossier personnel, store CoreTend ou Corbeille. Les tests n’appellent pas l’adaptateur Trash de production. La branche next est publique en source. Signature, notarisation, tag de release et distribution restent des étapes séparées.')}
}
labels={'en':['Home','Features','Privacy','Support','Developers'],'fr':['Accueil','Fonctions','Confidentialité','Assistance','Développement']}
for lang,content in pages.items():
 for key,(title,lead,h1,a,bh,b) in content.items():
  links=''.join(f'<a href="{name}.html">{label}</a>' for name,label in zip(('index','features','privacy','support','developer'),labels[lang]))
  body=f'''<!doctype html><html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta http-equiv="Content-Security-Policy" content="default-src 'self'; style-src 'self'; img-src 'self' data:; script-src 'none'; base-uri 'none'; object-src 'none'"><title>{title} — CoreTend</title><link rel="stylesheet" href="../site.css"></head><body><a class="skip" href="#main">{'Skip to content' if lang=='en' else 'Aller au contenu'}</a><header><a class="brand" href="index.html">CoreTend</a><nav aria-label="{'Main navigation' if lang=='en' else 'Navigation principale'}">{links}</nav><a href="../{'fr' if lang=='en' else 'en'}/{'index' if key=='home' else key}.html">{'Français' if lang=='en' else 'English'}</a></header><main id="main"><p class="eyebrow">{'Local preview · unreleased' if lang=='en' else 'Aperçu local · non publié'}</p><h1>{title}</h1><p>{lead}</p><section class="grid"><article class="card"><h2>{h1}</h2><p>{a}</p></article><article class="card"><h2>{bh}</h2><p>{b}</p></article></section><p class="notice">{'No download or public release is available.' if lang=='en' else 'Aucun téléchargement ni publication publique disponible.'}</p></main><footer><p>CoreTend · {'Local reconstruction' if lang=='en' else 'Reconstruction locale'} · 2026</p></footer></body></html>'''
  filename={'home':'index','features':'features','privacy':'privacy','support':'support','developer':'developer'}[key]
  Path(f'Website/{lang}/{filename}.html').write_text(body+'\n')
Path('Website/index.html').write_text('''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>CoreTend — choose language</title><link rel="stylesheet" href="site.css"></head><body><main><p class="eyebrow">Local preview · unreleased</p><h1>CoreTend</h1><p>Choose language / Choisir la langue</p><p><a href="en/index.html">English</a> · <a href="fr/index.html">Français</a></p></main></body></html>\n''')
