from pathlib import Path
import os
root = Path(__file__).resolve().parents[1]
os.chdir(root)
pages={
'en':{
'home':('A calmer way to understand your Mac','CoreTend is a local-first macOS disk and system explorer. This reconstruction is an unreleased local preview.','Current work','The preview can inspect a folder selected by you, report measured file sizes, and find exact duplicate content. It never changes files during a scan.','Eight destinations','Overview, Record, Cleanup, Explore, Duplicates, Applications, Integrity, and Performance define the product scope. Most domain views remain under construction.'),
'features':('Product scope','Eight destinations define the complete target. Only behavior marked as implemented in the local project has working code today.','Available in local preview','Folder scan with exclusions and symlink avoidance; SHA-256 exact duplicate identification; Trash-only file action boundary with fixture-only tests; versioned local event store; explicit-root read-only CLI.','Still to build','Cleanup review, exclusions and Trash action flow, application inventory, integrity signals, performance history, similar images, cloud-aware storage details, activity UI and export, migration flow, diagnostics, packaging and qualification.'),
'privacy':('Privacy by design','CoreTend is designed to work locally. This unreleased reconstruction sends no telemetry and has no account or cloud sync.','File access','The app preview scans only a folder you select. Scans read metadata and file contents only when needed for exact duplicate hashing. A scan never writes to the selected tree.','Actions and records','Any future file action must require review and confirmation, revalidate its target, and use macOS Trash only. Local event history and exports require explicit user controls; the full retention and export UI is not yet qualified.'),
'support':('Support','This local reconstruction has no public support channel and is not a released product.','For maintainers','Use the developer notes and test suite in the source repository. Report build failures with macOS version, architecture, command, and complete error output. Do not attach private file paths or database contents.','Before reporting','This project is an unpublished local reconstruction; no download or public support commitment exists.'),
'developer':('Developer notes','Build and test locally with Swift 6 and Swift Package Manager. No runtime package dependencies are used.','Commands','Run `swift test`, `swift build --product CoreTendApp`, and `swift build --product CoreTendCLI` from the reconstruction repository. Tests create unique temporary fixtures.','Safety boundary','Do not test against a real home directory, CoreTend store, or Trash. The production Trash adapter is not called by tests. No signing, notarization, publishing, push, or tag is part of this reconstruction.')},
'fr':{
'home':('Comprendre son Mac avec plus de clarté','CoreTend explore localement le disque et certains signaux système sur macOS. Cette reconstruction est un aperçu local non publié.','Travail actuel','L’aperçu peut examiner un dossier choisi par vous, afficher les tailles mesurées et repérer les doublons exacts. Une analyse ne modifie jamais les fichiers.','Huit destinations','Vue d’ensemble, Historique, Nettoyage, Explorer, Doublons, Applications, Intégrité et Performances composent le périmètre produit. La plupart des vues métier restent à construire.'),
'features':('Périmètre produit','Huit destinations forment la cible complète. Seuls les comportements déclarés comme implémentés dans le projet local fonctionnent aujourd’hui.','Disponible dans l’aperçu local','Analyse du dossier sélectionné avec exclusions et sans suivre les symlinks; doublons exacts par SHA-256; frontière d’action limitée à la Corbeille avec tests sur faux Trash; historique local versionné; CLI lecture seule à racine explicite.','Reste à construire','Revue et exclusions des candidats de nettoyage avec action Corbeille, inventaire des apps, signaux d’intégrité, historique des performances, images similaires, mesures cloud, vue et export d’activité, migration, diagnostics, paquet et qualification.'),
'privacy':('Confidentialité dès la conception','CoreTend est conçu pour fonctionner localement. Cette reconstruction non publiée n’envoie aucune télémétrie et ne propose ni compte ni synchronisation cloud.','Accès aux fichiers','L’aperçu analyse uniquement le dossier que vous choisissez. Il lit les métadonnées et le contenu seulement si nécessaire pour comparer exactement les doublons. Une analyse n’écrit jamais dans le dossier choisi.','Actions et historique','Toute action future doit demander revue et confirmation, revalider sa cible et utiliser seulement la Corbeille macOS. Historique local et exports demanderont des contrôles explicites; leur interface complète n’est pas encore qualifiée.'),
'support':('Assistance','Cette reconstruction locale ne dispose pas de canal d’assistance public et n’est pas un produit distribué.','Pour les mainteneurs','Consultez les notes de développement et la suite de tests dans le dépôt source. Pour un échec, joignez la version de macOS, l’architecture, la commande et le message complet. Ne joignez pas de chemins privés ni de base contenant vos données.','Avant tout signalement','Ce projet est une reconstruction locale non publiée; aucun téléchargement ni support public ne sont disponibles.'),
'developer':('Notes de développement','Construisez et vérifiez localement avec Swift 6 et Swift Package Manager. Aucune dépendance runtime externe.','Commandes','Depuis le dépôt de reconstruction : `swift test`, `swift build --product CoreTendApp` et `swift build --product CoreTendCLI`. Les tests créent des fixtures temporaires uniques.','Frontière de sûreté','Ne lancez pas les tests sur un vrai dossier personnel, store CoreTend ou Corbeille. Les tests n’appellent pas l’adaptateur Trash de production. Signature, notarisation, publication, push et tag sont exclus.')}
}
labels={'en':['Home','Features','Privacy','Support','Developers'],'fr':['Accueil','Fonctions','Confidentialité','Assistance','Développement']}
for lang,content in pages.items():
 for key,(title,lead,h1,a,bh,b) in content.items():
  links=''.join(f'<a href="{name}.html">{label}</a>' for name,label in zip(('index','features','privacy','support','developer'),labels[lang]))
  body=f'''<!doctype html><html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta http-equiv="Content-Security-Policy" content="default-src 'self'; style-src 'self'; img-src 'self' data:; script-src 'none'; base-uri 'none'; object-src 'none'"><title>{title} — CoreTend</title><link rel="stylesheet" href="../site.css"></head><body><a class="skip" href="#main">{'Skip to content' if lang=='en' else 'Aller au contenu'}</a><header><a class="brand" href="index.html">CoreTend</a><nav aria-label="{'Main navigation' if lang=='en' else 'Navigation principale'}">{links}</nav><a href="../{'fr' if lang=='en' else 'en'}/{'index' if key=='home' else key}.html">{'Français' if lang=='en' else 'English'}</a></header><main id="main"><p class="eyebrow">{'Local preview · unreleased' if lang=='en' else 'Aperçu local · non publié'}</p><h1>{title}</h1><p>{lead}</p><section class="grid"><article class="card"><h2>{h1}</h2><p>{a}</p></article><article class="card"><h2>{bh}</h2><p>{b}</p></article></section><p class="notice">{'No download or public release is available.' if lang=='en' else 'Aucun téléchargement ni publication publique disponible.'}</p></main><footer><p>CoreTend · {'Local reconstruction' if lang=='en' else 'Reconstruction locale'} · 2026</p></footer></body></html>'''
  filename={'home':'index','features':'features','privacy':'privacy','support':'support','developer':'developer'}[key]
  Path(f'Website/{lang}/{filename}.html').write_text(body+'\n')
Path('Website/index.html').write_text('''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>CoreTend — choose language</title><link rel="stylesheet" href="site.css"></head><body><main><p class="eyebrow">Local preview · unreleased</p><h1>CoreTend</h1><p>Choose language / Choisir la langue</p><p><a href="en/index.html">English</a> · <a href="fr/index.html">Français</a></p></main></body></html>\n''')
