#!/bin/sh
# Builds the sanitized external audit ZIP. Every tracked file is either
# staged into the package or listed in AUDIT_PACKAGE_EXCLUSIONS.md with a
# reason — the package is never called complete if a tracked file is
# silently missing without an explicit, documented exclusion.
set -euo pipefail
ROOT_DIR=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT_DIR"

DATE=$(date -u +%Y-%m-%d)
SHORT_SHA=$(git rev-parse --short HEAD)
NAME="MacCare-Local-Full-Audit-v0.7.1-${DATE}-${SHORT_SHA}"
STAGE="AuditPackages/${NAME}"

rm -rf "$STAGE"
mkdir -p "$STAGE"

# Explicit exclusion patterns (never staged) with reasons.
EXCLUDE_PATTERNS='^\.git($|/)|^\.build/|^build/|^DerivedData/|^\.swiftpm/|^\.claude/|^\.openclaude/|^AuditPackages/|^Configuration/PublicIdentity\.local\.json$|\.zip$|\.dmg$'

git ls-files > /tmp/audit-pkg-tracked.txt
included_count=0
excluded_list="/tmp/audit-pkg-excluded.txt"
: > "$excluded_list"

while IFS= read -r f; do
  if printf '%s\n' "$f" | grep -qE "$EXCLUDE_PATTERNS"; then
    echo "$f" >> "$excluded_list"
    continue
  fi
  dest="$STAGE/$f"
  mkdir -p "$(dirname "$dest")"
  cp "$f" "$dest"
  included_count=$((included_count + 1))
done < /tmp/audit-pkg-tracked.txt

# Real screenshot/evidence additions on top of the tracked-file mirror.
mkdir -p "$STAGE/AuditEvidence/Git"
git log --oneline -30 > "$STAGE/AuditEvidence/Git/log.txt"
git status > "$STAGE/AuditEvidence/Git/status.txt"
git branch -vv > "$STAGE/AuditEvidence/Git/branches.txt"

# AUDIT_PACKAGE_EXCLUSIONS.md — every excluded tracked file, with a reason.
{
  echo "# Audit Package Exclusions"
  echo
  echo "Generated by Scripts/build-audit-package.sh. Every git-tracked file not"
  echo "staged into this package is listed here with a reason — the package is"
  echo "never described as complete if a tracked file is silently missing."
  echo
  echo "| Path | Reason |"
  echo "|---|---|"
  while IFS= read -r f; do
    case "$f" in
      *.zip|*.dmg) reason="binary release artifact — checksums/inventories included instead" ;;
      .git|.git/*) reason="VCS internals" ;;
      .build/*|build/*|DerivedData/*|.swiftpm/*) reason="build output, not source" ;;
      .claude/*|.openclaude/*) reason="local tooling directory" ;;
      AuditPackages/*) reason="previous package staging output" ;;
      Configuration/PublicIdentity.local.json) reason="local override, not tracked/does not exist in this repo" ;;
      *) reason="matched exclusion pattern" ;;
    esac
    echo "| $f | $reason |"
  done < "$excluded_list"
} > "$STAGE/AUDIT_PACKAGE_EXCLUSIONS.md"

excluded_count=$(wc -l < "$excluded_list" | tr -d ' ')
tracked_count=$(wc -l < /tmp/audit-pkg-tracked.txt | tr -d ' ')

# AUDIT_PACKAGE_MANIFEST.json — four distinct commit fields, never one reused.
PRODUCT_SOURCE_COMMIT=$(git log -1 --format=%H -- Sources/ Tests/)
REQUIREMENTS_AUDIT_COMMIT=$(git log -1 --format=%H -- Documentation/requirements-traceability.json Documentation/MASTER_REQUIREMENTS_BASELINE.md)
CURRENT_HEAD=$(git rev-parse HEAD)

/usr/bin/python3 - "$STAGE" "$CURRENT_HEAD" "$PRODUCT_SOURCE_COMMIT" "$REQUIREMENTS_AUDIT_COMMIT" "$tracked_count" "$included_count" "$excluded_count" <<'PYEOF'
import json, sys
stage, current_head, product_commit, req_commit, tracked, included, excluded = sys.argv[1:8]
manifest = {
    "schemaVersion": 2,
    "product": "MacCare Local",
    "productVersion": "0.7.1",
    "auditDate_UTC": __import__("datetime").datetime.utcnow().strftime("%Y-%m-%d"),
    "CURRENT_HEAD": current_head,
    "PRODUCT_SOURCE_COMMIT": product_commit,
    "REQUIREMENTS_AUDIT_COMMIT": req_commit,
    "trackedFileCount": int(tracked),
    "includedFileCount": int(included),
    "excludedFileCount": int(excluded),
    "completenessCheck": "every tracked file is either included or listed in AUDIT_PACKAGE_EXCLUSIONS.md with a reason",
    "generatedBy": "Scripts/build-audit-package.sh",
}
with open(f"{stage}/AUDIT_PACKAGE_MANIFEST.json", "w") as f:
    json.dump(manifest, f, indent=2)
    f.write("\n")
PYEOF

total_accounted=$((included_count + excluded_count))
if [ "$total_accounted" -ne "$tracked_count" ]; then
  echo "FAIL: completeness check — $total_accounted accounted for vs $tracked_count tracked (some file neither included nor excluded)"
  exit 1
fi
echo "OK: completeness check — every tracked file is included ($included_count) or documented as excluded ($excluded_count)"
echo "Staged: $STAGE ($included_count included, $excluded_count excluded of $tracked_count tracked files)"

( cd AuditPackages && zip -X -r -q "${NAME}.zip" "${NAME}" )
SHA=$(shasum -a 256 "AuditPackages/${NAME}.zip" | awk '{print $1}')
SIZE=$(stat -f%z "AuditPackages/${NAME}.zip")
echo "Built: AuditPackages/${NAME}.zip"
echo "SHA-256: $SHA"
echo "Size: $SIZE bytes"
