#!/bin/sh
# Builds the sanitized external audit ZIP. Every tracked file is either
# staged into the package or listed in AUDIT_PACKAGE_EXCLUSIONS.md with a
# reason — the package is never called complete if a tracked file is
# silently missing without an explicit, documented exclusion.
set -euo pipefail
ROOT_DIR=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT_DIR"

DATE=$(date -u +%Y-%m-%d)
SHORT_SHA=$(git rev-parse --short HEAD)
PKG_VERSION=$(/usr/bin/python3 -c "import json; print(json.load(open('Configuration/PublicIdentity.example.json'))['marketingVersion'])")
PKG_BRANCH=$(git rev-parse --abbrev-ref HEAD)
NAME="MacCare-Local-Full-Audit-v${PKG_VERSION}-${DATE}-${SHORT_SHA}"
STAGE="AuditPackages/${NAME}"

rm -rf "$STAGE"
mkdir -p "$STAGE"

# Explicit exclusion patterns (never staged) with reasons.
EXCLUDE_PATTERNS='^\.git($|/)|^\.build/|^build/|^DerivedData/|^\.swiftpm/|^\.claude/|^\.openclaude/|^AuditPackages/|^Configuration/PublicIdentity\.local\.json$|\.zip$|\.dmg$|^Documentation/PROJECT_COMPLETE_AUDIT\.md$|^Documentation/PUBLICATION_AUDIT\.md$'

git ls-files > /tmp/audit-pkg-tracked.txt
included_count=0
excluded_list="/tmp/audit-pkg-excluded.txt"
: > "$excluded_list"

while IFS= read -r f; do
  if printf '%s\n' "$f" | grep -qE "$EXCLUDE_PATTERNS"; then
    echo "$f" >> "$excluded_list"
    continue
  fi
  dest="$STAGE/$f"
  mkdir -p "$(dirname "$dest")"
  cp "$f" "$dest"
  included_count=$((included_count + 1))
done < /tmp/audit-pkg-tracked.txt

# Real screenshot/evidence additions on top of the tracked-file mirror.
mkdir -p "$STAGE/AuditEvidence/Git"
git log --oneline -30 > "$STAGE/AuditEvidence/Git/log.txt"
git status > "$STAGE/AuditEvidence/Git/status.txt"
# git branch -vv prints absolute worktree paths, which leak the local
# developer's home directory — redact to a placeholder, same as PathValidator
# already does for on-disk paths (see Sources/SafetyCore redactPath).
git branch -vv | sed "s|$HOME|~|g" > "$STAGE/AuditEvidence/Git/branches.txt"

# AUDIT_PACKAGE_EXCLUSIONS.md — every excluded tracked file, with a reason.
{
  echo "# Audit Package Exclusions"
  echo
  echo "Generated by Scripts/build-audit-package.sh. Every git-tracked file not"
  echo "staged into this package is listed here with a reason — the package is"
  echo "never described as complete if a tracked file is silently missing."
  echo
  echo "| Path | Reason |"
  echo "|---|---|"
  while IFS= read -r f; do
    case "$f" in
      *.zip|*.dmg) reason="binary release artifact — checksums/inventories included instead" ;;
      .git|.git/*) reason="VCS internals" ;;
      .build/*|build/*|DerivedData/*|.swiftpm/*) reason="build output, not source" ;;
      .claude/*|.openclaude/*) reason="local tooling directory" ;;
      AuditPackages/*) reason="previous package staging output" ;;
      Configuration/PublicIdentity.local.json) reason="local override, not tracked/does not exist in this repo" ;;
      Documentation/PROJECT_COMPLETE_AUDIT.md|Documentation/PUBLICATION_AUDIT.md) reason="contains the developer's real local macOS account name in self-referential audit narrative text (an accepted, documented exception for check-private-data.sh's in-repo gate — see that script's own comment) — excluded specifically from this external-facing package, which leaves the machine" ;;
      *) reason="matched exclusion pattern" ;;
    esac
    echo "| $f | $reason |"
  done < "$excluded_list"
} > "$STAGE/AUDIT_PACKAGE_EXCLUSIONS.md"

excluded_count=$(wc -l < "$excluded_list" | tr -d ' ')
tracked_count=$(wc -l < /tmp/audit-pkg-tracked.txt | tr -d ' ')

# AUDIT_PACKAGE_MANIFEST.json — four distinct commit fields, never one reused.
# AUDIT_PACKAGE_COMMIT is CURRENT_HEAD at packaging time: this script requires a clean
# tree (checked below) before zipping, so "the commit that generated this package" and
# "current HEAD" are the same real commit, not a future/invented hash.
PRODUCT_SOURCE_COMMIT=$(git log -1 --format=%H -- Sources/ Tests/)
REQUIREMENTS_AUDIT_COMMIT=$(git log -1 --format=%H -- Documentation/requirements-traceability.json Documentation/MASTER_REQUIREMENTS_BASELINE.md)
CURRENT_HEAD=$(git rev-parse HEAD)

if [ -n "$(git status --short)" ]; then
  echo "FAIL: working tree not clean — refusing to build an audit package from a dirty tree."
  git status --short
  exit 1
fi

TESTS_JSON="Documentation/test-inventory.json"
TESTS_PASSED=$(/usr/bin/python3 -c "import json;print(json.load(open('$TESTS_JSON'))['passed'])")
TESTS_FAILED=$(/usr/bin/python3 -c "import json;print(json.load(open('$TESTS_JSON'))['failed'])")
TESTS_TOTAL=$(/usr/bin/python3 -c "import json;print(json.load(open('$TESTS_JSON'))['totalTests'])")
REQ_TOTAL=$(/usr/bin/python3 -c "import json;print(json.load(open('Documentation/requirements-traceability.json'))['requirementCount'])")

/usr/bin/python3 - "$STAGE" "$CURRENT_HEAD" "$PRODUCT_SOURCE_COMMIT" "$REQUIREMENTS_AUDIT_COMMIT" "$tracked_count" "$included_count" "$excluded_count" "$TESTS_TOTAL" "$TESTS_PASSED" "$TESTS_FAILED" "$REQ_TOTAL" "$PKG_VERSION" "$PKG_BRANCH" <<'PYEOF'
import json, sys
stage, current_head, product_commit, req_commit, tracked, included, excluded, tests_total, tests_passed, tests_failed, req_total, pkg_version, pkg_branch = sys.argv[1:14]
manifest = {
    "schemaVersion": 3,
    "product": "MacCare Local",
    "productVersion": pkg_version,
    "branch": pkg_branch,
    "auditDate_UTC": __import__("datetime").datetime.utcnow().strftime("%Y-%m-%d"),
    "CURRENT_HEAD": current_head,
    "PRODUCT_SOURCE_COMMIT": product_commit,
    "COMPLIANCE_AUDIT_COMMIT": current_head,
    "AUDIT_PACKAGE_SOURCE_COMMIT": current_head,
    "AUDIT_PACKAGE_GENERATION_COMMIT": current_head,
    "AUDIT_PACKAGE_COMMIT": current_head,
    "REQUIREMENTS_AUDIT_COMMIT": req_commit,
    "commitFieldNote": "This package was generated from a verified-clean working tree at CURRENT_HEAD "
                        "(git status --short was empty immediately before zipping). No new commit is made "
                        "purely to record a packaging event, so AUDIT_PACKAGE_COMMIT/AUDIT_PACKAGE_SOURCE_COMMIT/"
                        "AUDIT_PACKAGE_GENERATION_COMMIT/COMPLIANCE_AUDIT_COMMIT are all CURRENT_HEAD by "
                        "construction, not four independently-tracked values.",
    "trackedFileCount": int(tracked),
    "includedFileCount": int(included),
    "excludedFileCount": int(excluded),
    "testResults": {"total": int(tests_total), "passed": int(tests_passed), "failed": int(tests_failed),
                     "source": "Documentation/test-inventory.json"},
    "requirementsTotal": int(req_total),
    "featureStatusSource": "Documentation/feature-inventory.json",
    "visualCaptureStatus": "READY_FOR_MANUAL_QA — see Documentation/VISUAL_QA.md and KNOWN_LIMITATIONS.md for the current display-availability finding and what capture work remains",
    "completenessCheck": "every tracked file is either included or listed in AUDIT_PACKAGE_EXCLUSIONS.md with a reason",
    "generatedBy": "Scripts/build-audit-package.sh",
}
with open(f"{stage}/AUDIT_PACKAGE_MANIFEST.json", "w") as f:
    json.dump(manifest, f, indent=2)
    f.write("\n")
PYEOF

total_accounted=$((included_count + excluded_count))
if [ "$total_accounted" -ne "$tracked_count" ]; then
  echo "FAIL: completeness check — $total_accounted accounted for vs $tracked_count tracked (some file neither included nor excluded)"
  exit 1
fi
echo "OK: completeness check — every tracked file is included ($included_count) or documented as excluded ($excluded_count)"
echo "Staged: $STAGE ($included_count included, $excluded_count excluded of $tracked_count tracked files)"

# AUDIT_PACKAGE_FILELIST.txt — every file actually staged, relative paths.
( cd "$STAGE" && find . -type f | sed 's|^\./||' | sort ) > "$STAGE/AUDIT_PACKAGE_FILELIST.txt"

# AUDIT_PACKAGE_README.md — human explanation of the package.
cat > "$STAGE/AUDIT_PACKAGE_README.md" <<EOF
# MacCare Local — Audit Package (${NAME})

## What is in this package
A sanitized mirror of every git-tracked file in the repository at commit \`${CURRENT_HEAD}\`
(branch \`${PKG_BRANCH}\`, version ${PKG_VERSION}), plus generated evidence:
- \`AuditEvidence/Git/\` — real \`git log\`, \`git status\`, \`git branch -vv\` output captured at build time.
- \`AUDIT_PACKAGE_MANIFEST.json\` — machine-readable commit identities, test results, requirement count,
  feature-status source, and capture status.
- \`AUDIT_PACKAGE_EXCLUSIONS.md\` — every tracked file NOT staged, with a reason (binaries, VCS internals,
  build output, local-only config).
- \`AUDIT_PACKAGE_FILELIST.txt\` — flat list of every file actually staged in this package.
- \`AUDIT_PACKAGE_SHA256SUMS\` — SHA-256 of every staged file, for tamper detection after extraction.

## Which commit is which
- **PRODUCT_SOURCE_COMMIT** (\`${PRODUCT_SOURCE_COMMIT}\`): the latest commit touching \`Sources/\` or
  \`Tests/\` — this is the actual app being audited.
- **COMPLIANCE_AUDIT_COMMIT / AUDIT_PACKAGE_SOURCE_COMMIT / AUDIT_PACKAGE_GENERATION_COMMIT /
  AUDIT_PACKAGE_COMMIT** (all \`${CURRENT_HEAD}\`): this package was built from a verified-clean working
  tree at this commit. No separate "packaging commit" was made — see \`commitFieldNote\` in the manifest.
- **REQUIREMENTS_AUDIT_COMMIT** (\`${REQUIREMENTS_AUDIT_COMMIT}\`): the latest commit touching the
  requirements-traceability doc set.

## Historical vs current
Anything under \`AuditPackages/\` from a prior build, or any doc section explicitly marked
\`HISTORICAL\`/\`session N\` inside \`Documentation/\`, reflects an earlier point in the repo's history and
is preserved as a record, not restated as current. Current status lives in
\`Documentation/CURRENT_PROJECT_STATE.json\` and \`Documentation/CURRENT_AUDIT_STATE.json\`.

## Limitations
- No code signing or notarization (no Apple Developer ID available in this environment).
- No real-machine screenshot capture — this package was built in a non-interactive session with no
  display/window-capture access; see \`AUDIT_PACKAGE_MANIFEST.json\`'s \`visualCaptureStatus\` and
  \`Documentation/NON_COMPLIANCE_REGISTER.md\` (VIS-CAMPAIGN).
- Public-release identity fields (legal name/address, domain, security contact) are undecided
  placeholders — see \`Documentation/HUMAN_BLOCKERS.md\`.

## How to verify this archive
1. \`shasum -a 256 -c AUDIT_PACKAGE_SHA256SUMS\` from inside the extracted package root — every listed
   file must report OK.
2. Compare \`AUDIT_PACKAGE_MANIFEST.json\`'s \`CURRENT_HEAD\` against \`AuditEvidence/Git/log.txt\`'s top
   commit — they must match.
3. Cross-check \`testResults\` in the manifest against \`Documentation/test-inventory.json\` inside the
   package — same numbers, same source.
4. \`AuditEvidence/Git/status.txt\` should show a clean tree, confirming this was built from a
   non-dirty checkout.
EOF

( cd AuditPackages && zip -X -r -q "${NAME}.zip" "${NAME}" )
SHA=$(shasum -a 256 "AuditPackages/${NAME}.zip" | awk '{print $1}')
SIZE=$(stat -f%z "AuditPackages/${NAME}.zip")

# AUDIT_PACKAGE_SHA256SUMS — checksums of every staged file (computed pre-zip, from the stage dir).
( cd "$STAGE" && find . -type f ! -name AUDIT_PACKAGE_SHA256SUMS | sed 's|^\./||' | sort | xargs shasum -a 256 ) > "$STAGE/AUDIT_PACKAGE_SHA256SUMS"
# Re-zip once more so the SHA256SUMS file itself (computed after everything else existed) is included.
rm -f "AuditPackages/${NAME}.zip"
( cd AuditPackages && zip -X -r -q "${NAME}.zip" "${NAME}" )
SHA=$(shasum -a 256 "AuditPackages/${NAME}.zip" | awk '{print $1}')
SIZE=$(stat -f%z "AuditPackages/${NAME}.zip")

echo "Built: AuditPackages/${NAME}.zip"
echo "SHA-256: $SHA"
echo "Size: $SIZE bytes"
