#!/bin/sh
# Canonical website gate. The public site is generated by Website/build.py.
set -eu
ROOT="${CHECK_WEBSITE_ROOT:-$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)}"
cd "$ROOT"

python3 Website/build.py --output "${TMPDIR:-/tmp}/coretend-site-check-$$" >/dev/null
python3 Scripts/check-design-tokens.py
python3 Scripts/check-first-paint.py
python3 Scripts/check-retired-pages.py
if command -v node >/dev/null 2>&1 && [ -f Scripts/site/test-site.mjs ]; then
  if [ -n "${CORETEND_NODE_MODULES:-}" ] && [ -d "$CORETEND_NODE_MODULES" ]; then
    CORETEND_NODE_MODULES="$CORETEND_NODE_MODULES" node Scripts/site/test-site.mjs
  else
    node Scripts/site/test-site.mjs
  fi
else
  python3 Scripts/test-public-release-gate.py
  python3 Scripts/check-demo-fixtures.py
fi
