#!/usr/bin/env python3
"""Generates the Homebrew cask from the published release, never by hand.

A cask carries a version, a URL and a SHA-256. All three already exist, in
`Configuration/published-release.json`, which the release-sync gate writes and
which `DEVELOPMENT.md` says never to hand-edit. Typing them a second time into
a Ruby file is how a cask ends up pointing at a checksum that was true one
release ago — the failure mode is a download that Homebrew refuses, and the
user cannot tell whether the app or the packaging is broken.

So this derives, and `--check` fails when the committed cask no longer matches
the release — the ratchet this repository already applies to the settings
matrix and the architecture.

Usage:
    Scripts/generate-homebrew-cask.py            write homebrew/coretend.rb
    Scripts/generate-homebrew-cask.py --check    verify it matches the release
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
RELEASE = ROOT / "Configuration" / "published-release.json"
CASK = ROOT / "homebrew" / "coretend.rb"

TEMPLATE = '''# Generated by Scripts/generate-homebrew-cask.py from
# Configuration/published-release.json. Do not hand-edit: `--check` fails when
# this no longer matches the published release.
cask "coretend" do
  version "{version}"
  sha256 "{sha256}"

  url "https://github.com/ahmetbsbnr/coretend/releases/download/v#{{version}}/CoreTend-#{{version}}-arm64.dmg",
      verified: "github.com/ahmetbsbnr/coretend/"
  name "CoreTend"
  desc "Local, transparent and reversible storage care for macOS"
  homepage "https://coretend.ahmetbsbnr.com/"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on macos: ">= :{macos_symbol}"
  depends_on arch: :arm64

  app "CoreTend.app"

  # macOS caches app icons aggressively in LaunchServices, so a reinstall or
  # an upgrade can leave the Dock and Launchpad showing the previous icon.
  # Re-registering the bundle costs nothing and removes a support question
  # that has nothing to do with the app.
  postflight do
    system_command "/System/Library/Frameworks/CoreServices.framework/Versions/A/" \\
                   "Frameworks/LaunchServices.framework/Versions/A/Support/lsregister",
                   args: ["-f", "#{{appdir}}/CoreTend.app"],
                   sudo: false
  end

  # The paths CoreTend owns outside its bundle, taken from what
  # `Scripts/uninstall.sh` actually removes rather than from memory. The first
  # draft of this cask said "exactly two" and was wrong: the pre-rename product
  # left its own support directory and preferences, and a cask that ignores
  # them leaves data behind for precisely the users who have been here longest.
  # `uninstall.sh` treats the legacy pair as opt-in; `zap` is the explicit
  # "remove everything" verb, so here they belong.
  uninstall quit: "{bundle_id}"

  zap trash: [
    "~/Library/Application Support/CoreTend",
    "~/Library/Preferences/{bundle_id}.plist",
    "~/Library/Application Support/MacCareLocal",
    "~/Library/Application Support/MacCare Local",
    "~/Library/Preferences/local.maccare.app.plist",
  ]
end
'''

# macOS version number -> the symbol Homebrew expects.
MACOS_SYMBOLS = {
    "14.0": "sonoma", "14": "sonoma",
    "15.0": "sequoia", "15": "sequoia",
    "26.0": "tahoe", "26": "tahoe",
}


def bundle_identifier() -> str:
    plist = (ROOT / "Resources" / "Info.plist").read_text(encoding="utf-8")
    marker = "<key>CFBundleIdentifier</key>"
    start = plist.index(marker) + len(marker)
    chunk = plist[start:start + 200]
    return chunk.split("<string>")[1].split("</string>")[0]


def render() -> str:
    release = json.loads(RELEASE.read_text(encoding="utf-8"))
    for key in ("version", "dmgSHA256", "minimumMacOS"):
        if not release.get(key):
            raise SystemExit(f"cask: {RELEASE.name} has no {key}")
    minimum = str(release["minimumMacOS"])
    symbol = MACOS_SYMBOLS.get(minimum)
    if symbol is None:
        raise SystemExit(
            f"cask: no Homebrew symbol known for macOS {minimum}. Add it to "
            "MACOS_SYMBOLS rather than guessing — a wrong symbol silently "
            "installs on a system the app does not support.")
    return TEMPLATE.format(version=release["version"],
                           sha256=release["dmgSHA256"],
                           macos_symbol=symbol,
                           bundle_id=bundle_identifier())


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    expected = render()
    if args.check:
        if not CASK.exists():
            print(f"  - {CASK.relative_to(ROOT)} is missing")
            print("cask: run Scripts/generate-homebrew-cask.py and commit it")
            return 1
        if CASK.read_text(encoding="utf-8") != expected:
            print(f"  - {CASK.relative_to(ROOT)} no longer matches "
                  f"{RELEASE.name}")
            print("cask: run Scripts/generate-homebrew-cask.py and commit it")
            return 1
        release = json.loads(RELEASE.read_text(encoding="utf-8"))
        print(f"cask OK: v{release['version']}, sha256 matches the published DMG")
        return 0

    CASK.parent.mkdir(parents=True, exist_ok=True)
    CASK.write_text(expected, encoding="utf-8")
    release = json.loads(RELEASE.read_text(encoding="utf-8"))
    print(f"wrote {CASK.relative_to(ROOT)} for v{release['version']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
