#!/bin/sh
# Regenerates Documentation/test-inventory.json, Documentation/TEST_INVENTORY.md,
# and appends the raw run to Documentation/AUDIT_COMMANDS.log from an actual
# `Scripts/test.sh` run — counts are derived, never hand-typed.
set -euo pipefail
ROOT_DIR=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT_DIR"

COMMIT=$(git rev-parse HEAD)
DATE=$(date -u +%Y-%m-%d)
RAW=$(mktemp)
trap 'rm -f "$RAW"' EXIT

START=$(date +%s)
if Scripts/test.sh > "$RAW" 2>&1; then
  RESULT="PASS"
else
  RESULT="FAIL"
fi
END=$(date +%s)
WALL=$((END - START))

SUMMARY_LINE=$(grep -E "Test run with [0-9]+ tests? (in [0-9]+ suites? )?(passed|failed) after " "$RAW" | tail -1 || true)
if [ -z "$SUMMARY_LINE" ]; then
  echo "ERROR: Swift Testing summary was not found in Scripts/test.sh output." >&2
  exit 1
fi

TOTAL=$(printf '%s' "$SUMMARY_LINE" | sed -E 's/.*Test run with ([0-9]+) tests?.*/\1/')
if printf '%s' "$SUMMARY_LINE" | grep -Eq 'in [0-9]+ suites? '; then
  SUITES=$(printf '%s' "$SUMMARY_LINE" | sed -E 's/.*in ([0-9]+) suites?.*/\1/')
else
  # Swift 6.3 no longer prints the suite total in its final summary. Every
  # suite still emits exactly one terminal result line, so derive the count
  # from those lines instead of pinning a number in this script.
  SUITES=$(grep -Ec '^[✔✘] Suite ".*" (passed|failed) after ' "$RAW" || true)
fi
if [ "$SUITES" -eq 0 ]; then
  echo "ERROR: Swift Testing suite count could not be derived." >&2
  exit 1
fi
# Parameterized tests expand to multiple cases on one printed line, so counting
# lines undercounts; trust the run's own summary line instead: it says "passed"
# only when every one of TOTAL tests passed, otherwise the harness prints a
# distinct failure summary we treat conservatively as "not fully accounted".
if printf '%s' "$SUMMARY_LINE" | grep -q ' passed after '; then
  PASSED="$TOTAL"
  FAILED=0
else
  PASSED=0
  FAILED="$TOTAL"
fi
DURATION=$(printf '%s' "$SUMMARY_LINE" | sed -E 's/.*(passed|failed) after ([0-9.]+) seconds.*/\2/')

AUDIT_MARKER="\$ (audit $DATE, commit $(printf '%s' "$COMMIT" | cut -c1-7)) Scripts/test.sh"
if ! grep -Fqx "$AUDIT_MARKER" Documentation/AUDIT_COMMANDS.log; then
  {
    echo
    echo "$AUDIT_MARKER"
    cat "$RAW"
  } >> Documentation/AUDIT_COMMANDS.log
else
  echo "Audit output already recorded for $DATE at ${COMMIT}" >&2
fi

/usr/bin/python3 - "$COMMIT" "$DATE" "$TOTAL" "$SUITES" "$PASSED" "$FAILED" "$DURATION" "$WALL" "$RESULT" <<'PYEOF'
import json, os, re, subprocess, sys
commit, date, total, suites, passed, failed, duration, wall, result = sys.argv[1:10]

domains = []
tests_root = "Tests"
for module in sorted(os.listdir(tests_root)):
    path = os.path.join(tests_root, module)
    if not os.path.isdir(path):
        continue
    count = 0
    for root, _, files in os.walk(path):
        for fn in files:
            if fn.endswith(".swift"):
                with open(os.path.join(root, fn), encoding="utf-8") as f:
                    src = f.read()
                count += len(re.findall(r'@Test(\s|\()', src))
    domains.append({"module": module.replace("Tests", ""), "testFunctionsDeclared": count})

inventory = {
    "schemaVersion": 2,
    "auditDate_UTC": date,
    "commit": commit,
    "command": "Scripts/test.sh",
    "totalTests": int(total),
    "totalSuites": int(suites),
    "passed": int(passed),
    "failed": int(failed),
    "testRunDurationSeconds": float(duration) if duration else None,
    "wallTimeSeconds": int(wall),
    "result": result,
    "domains": domains,
    "generatedBy": "Scripts/generate-test-inventory.sh (derives counts from a real Scripts/test.sh run + @Test occurrence counts in Tests/, never hand-typed)",
    "historicalNote": "Prior versions of this file (audit sessions before 2026-07-21) recorded 86 tests / 27 suites at commit b33c06b. That was correct for its own commit; it is superseded, not falsified — see git history of this file for the historical snapshot.",
}
with open("Documentation/test-inventory.json", "w") as f:
    json.dump(inventory, f, indent=2)
    f.write("\n")

lines = []
lines.append("# TEST INVENTORY")
lines.append("")
lines.append(f"Evidence: `Scripts/test.sh` run on {date} (UTC) at commit `{commit}`.")
lines.append(f"Result: **{total} tests in {suites} suites, {result}, {passed} passed / {failed} failed** "
             f"({duration}s test-run time, {wall}s wall). Raw output appended to `Documentation/AUDIT_COMMANDS.log`.")
lines.append("")
lines.append("Generated by `Scripts/generate-test-inventory.sh` — counts come from parsing a real test run,")
lines.append("not typed by hand. Per-module `testFunctionsDeclared` counts `@Test` occurrences in each")
lines.append("`Tests/<Module>Tests/` directory (declared, not necessarily 1:1 with the executed count when")
lines.append("parameterized tests expand to multiple cases).")
lines.append("")
lines.append("## Declared @Test functions by module")
lines.append("")
lines.append("| Module | @Test functions declared |")
lines.append("|---|---|")
for d in domains:
    lines.append(f"| {d['module']} | {d['testFunctionsDeclared']} |")
lines.append("")
lines.append("## HISTORICAL (superseded)")
lines.append("")
lines.append("A prior audit session recorded 86 tests / 27 suites at commit `b33c06b8d68b9b03316821c3f6cfb17252f35011`")
lines.append("(2026-07-20). The repository has since grown to the current count above as new")
lines.append("modules and tests landed. That historical figure was correct for its own commit and is not restated")
lines.append("as current — see `git log -p Documentation/TEST_INVENTORY.md` for the full historical record.")
lines.append("")

with open("Documentation/TEST_INVENTORY.md", "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"OK: {total} tests / {suites} suites / result={result} written to test-inventory.json + TEST_INVENTORY.md")
PYEOF
