#!/usr/bin/env python3
"""Writes latest.json for a CoreTend release: the manifest the portfolio's sync reads.

Facts come from the release folder (file names, sizes, SHA-256) and git (the tag's commit,
clean tree). Usage: make_release_manifest.py --dir RELEASE_DIR --version 2.1.0 --build 210
"""
import argparse, hashlib, json, subprocess
from datetime import datetime, timezone
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument("--dir", required=True)
parser.add_argument("--version", required=True)
parser.add_argument("--build", required=True)
args = parser.parse_args()
folder = Path(args.dir)
tag = f"v{args.version}"
commit = subprocess.run(["git", "rev-parse", f"{tag}^{{commit}}"], capture_output=True, text=True, check=True).stdout.strip()
dirty = subprocess.run(["git", "status", "--porcelain", "--untracked-files=no"], capture_output=True, text=True, check=True).stdout.strip()

def facts(name):
    path = folder / name
    data = path.read_bytes()
    return hashlib.sha256(data).hexdigest(), len(data)

zip_name, dmg_name = f"CoreTend-{args.version}-arm64.zip", f"CoreTend-{args.version}-arm64.dmg"
zip_sha, zip_size = facts(zip_name)
dmg_sha, dmg_size = facts(dmg_name)
manifest = {
    "_comment": "GENERATED by Scripts/make_release_manifest.py from the release files and git. Do not hand-edit.",
    "schemaVersion": 2,
    "product": "CoreTend",
    "channel": "stable",
    "prerelease": False,
    "architecture": "arm64",
    "minimumMacOS": "14.0",
    "signed": True,
    "notarized": True,
    "knownLimitations": [
        "Developer ID signed (Team NSCUV5G738) and notarized by Apple; the app and DMG are stapled.",
        "Built and tested on one physical Mac (arm64, macOS 27); macOS 14 and 15 not yet tested on hardware.",
        "Full VoiceOver review not yet performed by a person.",
    ],
    "repositoryURL": "https://github.com/ahmetbsbnr/coretend",
    "websiteURL": "https://coretend.ahmetbsbnr.com",
    "license": "Apache-2.0",
    "telemetry": False,
    "accountRequired": False,
    "version": args.version,
    "build": args.build,
    "zipName": zip_name, "zipSHA256": zip_sha, "zipSize": zip_size,
    "dmgName": dmg_name, "dmgSHA256": dmg_sha, "dmgSize": dmg_size,
    "releaseNotes": f"Documentation/Release/{'.'.join(args.version.split('.')[:2])}-notes.md",
    "sourceCommit": commit,
    "releaseTag": tag,
    "treeState": "dirty" if dirty else "clean",
    "generatedAt_UTC": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    "generatedBy": "Scripts/make_release_manifest.py",
}
(folder / "latest.json").write_text(json.dumps(manifest, indent=2) + "\n")
print(f"latest.json for {tag} at {commit[:8]} ({manifest['treeState']})")
