#!/bin/bash
# Writes Configuration/published-release.json from the release GitHub is
# actually serving.
#
# The website's download button must point at a file that exists. Reading the
# GitHub API at build time would make the site build depend on the network and
# on rate limits, and reading dist/latest.json would depend on someone having
# just built locally. So the pointer is committed, and this script is what
# updates it — run by the release workflow after publishing, and runnable by
# hand.
#
# GitHub's /releases/latest deliberately skips prereleases, so it cannot be
# used while the current release is an -rc. This asks for the newest published
# release of any kind instead.
set -euo pipefail
cd "$(dirname "$0")/.."

REPO="${CORETEND_REPO:-ahmetbsbnr/coretend}"
OUT="Configuration/published-release.json"

latest=$(gh api "repos/$REPO/releases" --jq '[.[]|select(.draft|not)]|sort_by(.published_at)|reverse|.[0]')
[ -n "$latest" ] || { echo "no published release found"; exit 1; }

tag=$(printf '%s' "$latest" | /usr/bin/python3 -c "import json,sys;print(json.load(sys.stdin)['tag_name'])")

# The manifest published with that release is the authority for checksums and
# sizes; the API is only used to find which release is newest.
tmp=$(mktemp -d)
gh release download "$tag" -R "$REPO" --pattern latest.json --dir "$tmp" --clobber >/dev/null

/usr/bin/python3 - "$latest" "$tmp/latest.json" "$OUT" "$REPO" <<'PY'
import json, os, re, sys, tempfile
api = json.loads(sys.argv[1])
manifest = json.load(open(sys.argv[2]))
out, repo = sys.argv[3], sys.argv[4]

tag = api["tag_name"]
assets = {a["name"]: a["browser_download_url"] for a in api.get("assets", [])}
dmg = manifest["dmgName"]
if dmg not in assets:
    sys.exit(f"the manifest names {dmg} but the release does not publish it")

record = {
    "_comment": "Tracked record of the release currently served by GitHub. "
                "Generated by the release synchronization gate; do not hand-edit.",
    "schemaVersion": 1,
    "product": "CoreTend",
    "version": manifest["version"],
    "channel": manifest.get("channel", ""),
    "prerelease": bool(api.get("prerelease")),
    "tag": tag,
    "sourceCommit": manifest.get("sourceCommit", ""),
    "releaseURL": api["html_url"],
    "repositoryURL": f"https://github.com/{repo}",
    "dmgName": dmg,
    "dmgURL": assets[dmg],
    "dmgSHA256": manifest.get("dmgSHA256", ""),
    "dmgSize": manifest.get("dmgSize", 0),
    "zipName": manifest.get("zipName", ""),
    "zipURL": assets.get(manifest.get("zipName", ""), ""),
    "zipSHA256": manifest.get("zipSHA256", ""),
    "zipSize": manifest.get("zipSize", 0),
    "signed": manifest.get("signed", False),
    "notarized": manifest.get("notarized", False),
    "minimumMacOS": manifest.get("minimumMacOS", "14.0"),
    "architecture": manifest.get("architecture", "arm64"),
    "publishedAt": api.get("published_at", ""),
}

download_rule = re.compile(
    r'(\{\s*"source"\s*:\s*"/download"\s*,\s*"destination"\s*:\s*)'
    r'"(?:[^"\\]|\\.)*"'
)


def prepared_route_config(path, download_url):
    with open(path, encoding="utf-8") as handle:
        current_text = handle.read()
    current = json.loads(current_text)
    rules = [rule for rule in current.get("redirects", []) if rule.get("source") == "/download"]
    if len(rules) != 1:
        raise SystemExit(f"{path} must contain exactly one /download redirect")
    if rules[0].get("permanent") is not False:
        raise SystemExit(f"{path} /download redirect must remain temporary")
    updated_text, count = download_rule.subn(
        lambda match: match.group(1) + json.dumps(download_url),
        current_text,
    )
    if count != 1:
        raise SystemExit(f"{path} /download redirect is not in the reviewed shape")
    updated = json.loads(updated_text)
    updated_rule = [rule for rule in updated["redirects"] if rule.get("source") == "/download"][0]
    if updated_rule.get("destination") != download_url:
        raise SystemExit(f"{path} /download redirect did not synchronize")
    return updated_text


def atomic_write(path, text):
    directory = os.path.dirname(path) or "."
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{os.path.basename(path)}.", dir=directory)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_name, path)
    finally:
        if os.path.exists(temporary_name):
            os.unlink(temporary_name)


# Prepare and validate every derived file before replacing any of them. The
# commit then promotes the canonical record and both deployment contracts as a
# single reviewed change.
route_configs = {
    path: prepared_route_config(path, assets[dmg])
    for path in ("vercel.json", "Website/vercel.json")
}
atomic_write(out, json.dumps(record, indent=2, ensure_ascii=False) + "\n")
for path, content in route_configs.items():
    atomic_write(path, content)

print(f"published-release.json -> {manifest['version']} ({tag})")
print(f"  dmg: {assets[dmg]}")
print("  redirects: vercel.json, Website/vercel.json")
PY
rm -rf "$tmp"
