#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: The CoreTend Authors
#
# Writes dist/release-manifest.json: one auditable record of what a release is,
# derived from the artifacts that were actually produced rather than retyped.
#
# It exists so a release can be audited months later without trusting a CI log
# or this conversation: which commit, which tag, which run, which key, which
# bytes. Published as a release asset alongside the artifacts it describes.
#
# Contains no secret: key IDs, hashes and identifiers are all public.
#
# Usage: Scripts/write-release-manifest.sh <version> <channel> <sourceSha> <runId>
set -euo pipefail
cd "$(dirname "$0")/.."

VERSION="${1:?usage: $0 <version> <channel> <sourceSha> <runId>}"
CHANNEL="${2:?}"
SOURCE_SHA="${3:?}"
RUN_ID="${4:?}"

DIST="dist"
[ -d "$DIST" ] || { echo "write-release-manifest.sh: FAIL — $DIST is missing; run build-release.sh first"; exit 1; }

MINISIGN_KEY=$(/usr/bin/python3 Scripts/resolve-minisign-key.py "$VERSION")

/usr/bin/python3 - "$VERSION" "$CHANNEL" "$SOURCE_SHA" "$RUN_ID" "$MINISIGN_KEY" <<'PYEOF'
import hashlib, json, os, sys, datetime, pathlib

version, channel, source_sha, run_id, minisign_key = sys.argv[1:6]
dist = pathlib.Path("dist")

def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for block in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()

# Only this version's artifacts, hashed from the same bytes that get uploaded.
# Scoped by version on purpose: a stale file left in dist/ by an earlier build
# must not be described as part of this release, and the manifest must list
# exactly what the workflow uploads.
def belongs(name: str) -> bool:
    if name == "release-manifest.json":
        return False
    if version in name:
        return True
    return name in {"latest.json", "SHA256SUMS", "minisign.pub"} or name.endswith(".minisig")

assets = []
for path in sorted(dist.iterdir()):
    if not path.is_file() or not belongs(path.name):
        continue
    assets.append({
        "name": path.name,
        "size": path.stat().st_size,
        "sha256": sha256(path),
    })

if not any(a["name"].endswith(".dmg") for a in assets):
    sys.exit("write-release-manifest.sh: FAIL — no DMG for this version in dist/")
if not any(a["name"].endswith(".zip") for a in assets):
    sys.exit("write-release-manifest.sh: FAIL — no ZIP for this version in dist/")

latest = json.loads((dist / "latest.json").read_text(encoding="utf-8"))

manifest = {
    "_comment": (
        "Machine-readable record of one CoreTend release, generated by "
        "Scripts/write-release-manifest.sh from the artifacts actually built. "
        "Contains no secret. Audit a release against this rather than against a CI log."
    ),
    "schemaVersion": 1,
    "product": "CoreTend",
    "version": version,
    "tag": f"v{version}",
    "channel": channel,
    "prerelease": bool(latest.get("prerelease")),
    "sourceCommit": source_sha,
    "workflowRunId": run_id,
    "builtAtUTC": datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    "bundleIdentifier": "com.ahmetbsbnr.coretend",
    "minimumMacOS": latest.get("minimumMacOS"),
    "architectures": [latest.get("architecture")],
    "appleTeamId": "NSCUV5G738",
    "signed": bool(latest.get("signed")),
    "notarized": bool(latest.get("notarized")),
    "minisignKeyId": minisign_key,
    "sbom": f"coretend-{version}-sbom.spdx.json",
    "assets": assets,
    "_verify": (
        "Scripts/verify-published-artifacts.sh <version> re-downloads these assets "
        "and re-checks every hash, signature, staple and Gatekeeper verdict."
    ),
}

out = dist / "release-manifest.json"
out.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
print(f"write-release-manifest.sh: wrote {out} ({len(assets)} assets, key {minisign_key})")
PYEOF
